### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by albertograva** [saccon/CXF_in#1]
hi! 
I can't login to https://www.prgcloud.com/auth/login.php even if I have requested a new password to the system. 
thx a lot

3.8.1-Zanzibar e ubuntu 18.04

**Comment by RobiFag** [comment]
Hi!
I have a similar problem..I'm able to log in from https://www.prgcloud.com/auth/login.php using a browser but if I try to log in from the plugin GUI I get this error:
2019-12-16T10:52:34     WARNING    Traceback (most recent call last):

              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 1317, in do_open
              encode_chunked=req.has_header('Transfer-encoding'))
              File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1229, in request
              self._send_request(method, url, body, headers, encode_chunked)
              File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1275, in _send_request
              self.endheaders(body, encode_chunked=encode_chunked)
              File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1224, in endheaders
              self._send_output(message_body, encode_chunked=encode_chunked)
              File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1016, in _send_output
              self.send(msg)
              File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 956, in send
              self.connect()
              File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1392, in connect
              server_hostname=server_hostname)
              File "C:\OSGEO4~1\apps\Python37\lib\ssl.py", line 412, in wrap_socket
              session=session
              File "C:\OSGEO4~1\apps\Python37\lib\ssl.py", line 850, in _create
              self.do_handshake()
              File "C:\OSGEO4~1\apps\Python37\lib\ssl.py", line 1108, in do_handshake
              self._sslobj.do_handshake()
             ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1045)
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/roberta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Cxf_in\catdialog.py", line 329, in connectgeodb
              with contextlib.closing(urllib.request.urlopen(req)) as x:
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 222, in urlopen
              return opener.open(url, data, timeout)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 525, in open
              response = self._open(req, data)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 543, in _open
              '_open', req)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 503, in _call_chain
              result = func(*args)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 1360, in https_open
              context=self._context, check_hostname=self._check_hostname)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 1319, in do_open
              raise URLError(err)
             urllib.error.URLError: 
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/roberta/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Cxf_in\catdialog.py", line 334, in connectgeodb
              except urllib.URLError as err:
             AttributeError: module 'urllib' has no attribute 'URLError'

When I try to add the cxf file to the spatialite DB, I get the same error. The DB has been created, the layers are loaded in QGIS but they are empty. I can see the data if I use 'Load cxf in memory layer' but when I try to connect I get the error again.

I'm using Qgis 3.4.14 both on Windows8 and Ubuntu 18.04 and the plugin version is 9.2

**Comment by pigreco** [comment]
Ciao Fabio,
confermo pure io. :-)

**Comment by ivn951** [comment]
Hi there,
the same problem on **macOS** machine : 

- **Python version: 3.7.3** (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
- **QGIS version: 3.10.0**-A Coruña A Coruña, 6c816b4204 .

**_Underline_**:

>module 'urllib' has no attribute 'URLError' 
>CERTIFICATE_VERIFY_FAILED  -- certificate has expired (_ssl.c:1056)

urllib has different API on python 2 and 3
Regards
