### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by ludovico85** [saccon/CXF_in#6]
**Issue**: when installing the plugin the following error appears:

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ludov/AppData/Roaming/QGIS/QGIS3\profiles\Ludovico_GIS/python/plugins\Cxf_in\__init__.py", line 35, in classFactory
    from .cxf_in import Cxf_in
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ludov/AppData/Roaming/QGIS/QGIS3\profiles\Ludovico_GIS/python/plugins\Cxf_in\cxf_in.py", line 30, in 
    from .catdialog import catDialog
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ludov/AppData/Roaming/QGIS/QGIS3\profiles\Ludovico_GIS/python/plugins\Cxf_in\catdialog.py", line 40, in 
    import sys, os, imp, re
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'
```

**QGIS version**:  3.34.6

**Python version**: 3.12.3

**Note**: the error can be solved by changing the catdialog.py at line 40
from `import sys, os, imp, re` to `import sys, os, importlib, re`

**Comment by brunellop** [comment]
@ludovico85 @saccon
Grazie mille!!!!!

**Comment by agiudiceandrea** [comment]
Sarebbe molto utile se @saccon aggiornasse questo repository e se apportasse la modifica necessaria affinché il plugin possa funzionare.

**Comment by sn0rkyITA** [comment]
appena corretto! ora funziona!! caricando i cxf in locale (ora l'agenzia delle entrate permette il download gratuito dei fogli cxf già georiferiti ad esempio epsg3003) non carica correttamente i dati numerici (vedo diversi errori)

**Comment by ludovico85** [comment]
> appena corretto! ora funziona!! caricando i cxf in locale (ora l'agenzia delle entrate permette il download gratuito dei fogli cxf già georiferiti ad esempio epsg3003) non carica correttamente i dati numerici (vedo diversi errori)

Gli errori si verificano se salvi nel db giusto? Mentre come layer temporaneo funziona?

**Comment by agiudiceandrea** [comment]
In realtà, basta modificare la linea da `from import sys, os, imp, re` a `import sys, os, re`, in quanto il modulo `importlib` viene già importato precedentemente nel codice del plugin.
Comunque ho effettuato un fork di questo repository https://github.com/agiudiceandrea/CXF_in e ho creato una nuova versione funzionante https://github.com/agiudiceandrea/CXF_in/releases/tag/9.2.1 che può essere installata tramite file zip senza dover modificare manualmente il codice sorgente del plugin dopo l'installazione.

**Comment by sn0rkyITA** [comment]
> > appena corretto! ora funziona!! caricando i cxf in locale (ora l'agenzia delle entrate permette il download gratuito dei fogli cxf già georiferiti ad esempio epsg3003) non carica correttamente i dati numerici (vedo diversi errori)
> 
> Gli errori si verificano se salvi nel db giusto? Mentre come layer temporaneo funziona?

non sono per nulla esperto, ho importato un cxf "di quelli nuovi" già in roma40 e quindi in layer temporaneo, sono usciti una serie di errori (se serve li recupero rifacendo tutti i passaggi)

**Comment by agiudiceandrea** [comment]
@sn0rkyITA, se indichi esattamente gli errori riscontrati e fornisci il file utilizzato e i comandi eseguiti, ci potrebbe essere la possibilità di risolvere tali problemi, come è stato possibile con questo. Magari sarebbe meglio creare un nuovo issue report apposito.

**Comment by brunellop** [comment]
> > > appena corretto! ora funziona!! caricando i cxf in locale (ora l'agenzia delle entrate permette il download gratuito dei fogli cxf già georiferiti ad esempio epsg3003) non carica correttamente i dati numerici (vedo diversi errori)
> > 
> > 
> > Gli errori si verificano se salvi nel db giusto? Mentre come layer temporaneo funziona?
> 
> non sono per nulla esperto, ho importato un cxf "di quelli nuovi" già in roma40 e quindi in layer temporaneo, sono usciti una serie di errori (se serve li recupero rifacendo tutti i passaggi)

Ho importato i CXF in Memory Layer e confermo la presenza degli errori utilizzando l'ultima versione LTR 3.34, ho provato anche con la vecchia versione 3.28 riscontrando gli stessi problemi. I layer rimangono aperti in editing, i testi non prendono la rotazione corretta e poi una serie di errori sulla memorizzazione degli attributi.

![Image](https://github.com/user-attachments/assets/9abcb813-3f9d-4a6a-9ab3-8b30154c73a1)

**Comment by agiudiceandrea** [comment]
@brunellop, è probabile che le specifiche tecniche del formato CXF non siano più le stesse di quando il plugin è stato creato.
Sarebbe utile, come già indicato, rendere disponibile un file CXF attuale.

**Comment by ludovico85** [comment]
> > > > appena corretto! ora funziona!! caricando i cxf in locale (ora l'agenzia delle entrate permette il download gratuito dei fogli cxf già georiferiti ad esempio epsg3003) non carica correttamente i dati numerici (vedo diversi errori)
> > > 
> > > 
> > > Gli errori si verificano se salvi nel db giusto? Mentre come layer temporaneo funziona?
> > 
> > 
> > non sono per nulla esperto, ho importato un cxf "di quelli nuovi" già in roma40 e quindi in layer temporaneo, sono usciti una serie di errori (se serve li recupero rifacendo tutti i passaggi)
> 
> Ho importato i CXF in Memory Layer e confermo la presenza degli errori utilizzando l'ultima versione LTR 3.34, ho provato anche con la vecchia versione 3.28 riscontrando gli stessi problemi. I layer rimangono aperti in editing, i testi non prendono la rotazione corretta e poi una serie di errori sulla memorizzazione degli attributi.
> 
> ![Image](https://github.com/user-attachments/assets/9abcb813-3f9d-4a6a-9ab3-8b30154c73a1)

L'errore del salvataggio accade solo nel caso venga salvato come layer temporaneo ed è dovuto ad una questione di lunghezza dei campi del layer che viene creato. L'errore esisteva anche in passato

**Comment by sn0rkyITA** [comment]
> [@brunellop](https://github.com/brunellop), è probabile che le specifiche tecniche del formato CXF non siano più le stesse di quando il plugin è stato creato. Sarebbe utile, come già indicato, rendere disponibile un file CXF attuale.

l'ho allegato al problema che ho aperto.

**Comment by sn0rkyITA** [comment]
@ludovico85 @agiudiceandrea @brunellop @saccon 

sarebbe utile, anche in considerazione del "rinnovato" cxf georeferenziato all'origine, creare qualcosa di semplice, magari integrando quanto già sviluppato per l'integrazione dei dati censuari con i file .FAB, .SOG, .TIT (pur non conoscendone la reale reperibilità)

io sono purtroppo un utilizzatore passivo (non avendo purtroppo grosse capacità di programmazione) ma un supporto di qualche tipo posso darlo senza problemi, anche perché sarebbe un plugin veramente molto utile!!

**Comment by ludovico85** [comment]
> [@ludovico85](https://github.com/ludovico85) [@agiudiceandrea](https://github.com/agiudiceandrea) [@brunellop](https://github.com/brunellop) [@saccon](https://github.com/saccon)
> 
> sarebbe utile, anche in considerazione del "rinnovato" cxf georeferenziato all'origine, creare qualcosa di semplice, magari integrando quanto già sviluppato per l'integrazione dei dati censuari con i file .FAB, .SOG, .TIT (pur non conoscendone la reale reperibilità)
> 
> io sono purtroppo un utilizzatore passivo (non avendo purtroppo grosse capacità di programmazione) ma un supporto di qualche tipo posso darlo senza problemi, anche perché sarebbe un plugin veramente molto utile!!

Io ho già fatto qualcosa in merito! https://github.com/ludovico85/gestione-dati-censuari-catasto-postgresql-qgis

**Comment by sn0rkyITA** [comment]
> > [@ludovico85](https://github.com/ludovico85) [@agiudiceandrea](https://github.com/agiudiceandrea) [@brunellop](https://github.com/brunellop) [@saccon](https://github.com/saccon)
> > sarebbe utile, anche in considerazione del "rinnovato" cxf georeferenziato all'origine, creare qualcosa di semplice, magari integrando quanto già sviluppato per l'integrazione dei dati censuari con i file .FAB, .SOG, .TIT (pur non conoscendone la reale reperibilità)
> > io sono purtroppo un utilizzatore passivo (non avendo purtroppo grosse capacità di programmazione) ma un supporto di qualche tipo posso darlo senza problemi, anche perché sarebbe un plugin veramente molto utile!!
> 
> Io ho già fatto qualcosa in merito! https://github.com/ludovico85/gestione-dati-censuari-catasto-postgresql-qgis

fantastico!
ma è un plugin qgis?
dove potremmo parlarne in modo più comodo?
sarebbe interessante integrare la parte di importazione in memory layer di saccon e rendere il tutto più comodo!
sarei il primo utilizzatore di un plugin del genere :D

**Comment by ludovico85** [comment]
No, non è un plugin ma ci sono i modelli di QGIS pronti all'uso (o quasi).
La gestione per ora è complicata perché è necessario un db postgresql.
Dovrei implementare la possibilità di utilizzare un db in locale ma non ho
proprio il tempo.

Ph.D., Dr. For. Ludovico Frate
________________________________________________
Studio Tecnico Forestale e GIS
*Via Montalto 17, 86087 - Rionero Sannitico (IS) - ITALIA*
*Socio Amministratore **Ecoview s.r.l. <https://www.naturagis.it/>*

*Collaboratore presso Unimol EnviXlab <http://envixlab.unimol.it/>*
*Cel: +39 3333767557*
*P.IVA 00960030948*
*poe: ***@***.******@***.***
*pec:* ***@***.***
*➡️ *
*LinkedIn
<https://www.linkedin.com/in/ludovico-frate-a387aa57?trk=hp-identity-name>*
<https://www.researchgate.net/profile/Ludovico_Frate?ev=hdr_xprf&_sg=lGaI2daIBO6kPmtye069ckFfDExcPoNVKJHrqvQEPQmsmnHolvnRZzPQdcyxs1g7>*
<http://envixlab.unimol.it/>*
*➡️** Research Gate
<https://www.researchgate.net/profile/Ludovico_Frate?ev=hdr_xprf&_sg=lGaI2daIBO6kPmtye069ckFfDExcPoNVKJHrqvQEPQmsmnHolvnRZzPQdcyxs1g7>*
<https://github.com/ludovico85>* <http://envixlab.unimol.it/>*
*➡️* GitHub <https://github.com/ludovico85>




Il giorno lun 27 gen 2025 alle ore 13:34 sn0rkyITA ***@***.***>
ha scritto:

**Comment by brunellop** [comment]
> > > > > appena corretto! ora funziona!! caricando i cxf in locale (ora l'agenzia delle entrate permette il download gratuito dei fogli cxf già georiferiti ad esempio epsg3003) non carica correttamente i dati numerici (vedo diversi errori)
> > > > 
> > > > 
> > > > Gli errori si verificano se salvi nel db giusto? Mentre come layer temporaneo funziona?
> > > 
> > > 
> > > non sono per nulla esperto, ho importato un cxf "di quelli nuovi" già in roma40 e quindi in layer temporaneo, sono usciti una serie di errori (se serve li recupero rifacendo tutti i passaggi)
> > 
> > 
> > Ho importato i CXF in Memory Layer e confermo la presenza degli errori utilizzando l'ultima versione LTR 3.34, ho provato anche con la vecchia versione 3.28 riscontrando gli stessi problemi. I layer rimangono aperti in editing, i testi non prendono la rotazione corretta e poi una serie di errori sulla memorizzazione degli attributi.
> > ![Image](https://github.com/user-attachments/assets/9abcb813-3f9d-4a6a-9ab3-8b30154c73a1)
> 
> L'errore del salvataggio accade solo nel caso venga salvato come layer temporaneo ed è dovuto ad una questione di lunghezza dei campi del layer che viene creato. L'errore esisteva anche in passato

Ho effettuato alcune prove, tenendo presente che, quando ho iniziato a usare il plugin, ero certo che funzionasse senza errori.
Con l'ultima versione LTR 3.34 ho caricato i vari file CXF presenti nel mio archivio, risalenti al periodo dal 2017 a oggi, in tutti i casi ho riscontrato la ripetizione dello stesso errore.
A questo punto, facendo riferimento approssimativo alla data in cui il plugin è stato rilasciato, ho scaricato una vecchia versione di QGIS 3.10, in questo caso l'errore non si verifica, a questo punto bisognerebbe capire da quale versione è iniziato il problema.
